project:
  type: website

website:
  title: "Quarto Workshop LMU OSC"
  page-navigation: true
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
  navbar:
    left:
      - text: "1. Welcome"
        href: "index.qmd"
      - text: "2. Quarto Tutorials"
        file: "quarto_tutorials.qmd"
      - text: "3. Tips and Comments"
        file: "comments.qmd"
      - text: "4. Links"
        file: "links.qmd"
      - text: "About"
        file: "about.qmd"

  sidebar:
    - title: "2. Quarto Tutorials"
      style: "docked"
      background: light
      contents:
        - section: "2. Quarto Tutorials"
          contents:
            - quarto_tutorials.qmd
            - preparations.qmd
        - section: "  Quarto Tutorials"
          contents:
            - get-started_1.qmd
            - get-started_2.qmd
            - get-started_3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    df-print: paged
    code-overflow: wrap

from: markdown+emoji
