project:
  type: website

website:
  title: "Quarto Workshop LMU OSC Summer School 2023"
  page-navigation: true
  page-footer: "Copyright by Lehrstuhl Psychologische Methodenlehre und Diagnostik, LMU Munich" 
  navbar:
    left:
      - text: "1. Welcome"
        href: "index.qmd"
      - text: "2. Quarto Tutorials"
        file: "quarto_tutorials.qmd"
      - text: "3. Discussion"
        file: "discussion.qmd"
      - text: "4. Links"
        file: "links.qmd"
      - text: "About"
        file: "about.qmd"

  sidebar:
    - title: "2. Quarto Tutorials"
      style: "docked"
      background: light
      contents:
        - quarto_tutorials.qmd
        - preparations.qmd
        - get-started_1.qmd
        - get-started_2.qmd
        - get-started_3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true



